export const locatii = {
  România: [
    "Alba Iulia",
    "Arad",
    "Pitești",
    "Bacău",
    "Oradea",
    "Bistrița",
    "Botoșani",
    "Brașov",
    "Brăila",
    "Buzău",
    "Reșița",
    "Călărași",
    "Cluj-Napoca",
    "Constanța",
    "Sfântu Gheorghe",
    "Craiova",
    "Galați",
    "Giurgiu",
    "Târgu Jiu",
    "Miercurea Ciuc",
    "Deva",
    "Slobozia",
    "Iași",
    "București",
    "Baia Mare",
    "Drobeta-Turnu Severin",
    "Târgu Mureș",
    "Piatra Neamț",
    "Slatina",
    "Ploiești",
    "Satu Mare",
    "Zalău",
    "Sibiu",
    "Suceava",
    "Alexandria",
    "Timișoara",
    "Tulcea",
    "Vaslui",
    "Râmnicu Vâlcea",
    "Focșani",
  ],
  Franța: [
    "Paris",
    "Marseille",
    "Lyon",
    "Toulouse",
    "Nice",
    "Nantes",
    "Strasbourg",
    "Montpellier",
  ],
  Germania: [
    "Berlin",
    "Hamburg",
    "München",
    "Köln",
    "Frankfurt",
    "Stuttgart",
    "Düsseldorf",
    "Dortmund",
    "Essen",
    "Leipzig",
  ],
  Italia: [
    "Roma",
    "Milano",
    "Napoli",
    "Torino",
    "Palermo",
    "Genova",
    "Bologna",
    "Firenze",
  ],
  Spania: [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Sevilla",
    "Zaragoza",
    "Málaga",
    "Murcia",
    "Palma de Mallorca",
  ],
  "Regatul Unit": [
    "Londra",
    "Birmingham",
    "Manchester",
    "Glasgow",
    "Newcastle",
    "Sheffield",
    "Liverpool",
    "Leeds",
  ],
  "Statele Unite": [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
  ],
  Australia: [
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Gold Coast",
    "Canberra",
    "Newcastle",
    "Wollongong",
  ],
  Canada: [
    "Toronto",
    "Montreal",
    "Vancouver",
    "Calgary",
    "Edmonton",
    "Ottawa",
    "Winnipeg",
    "Quebec City",
    "Hamilton",
  ],
  Japonia: [
    "Tokyo",
    "Osaka",
    "Yokohama",
    "Nagoya",
    "Sapporo",
    "Fukuoka",
    "Kobe",
    "Kyoto",
    "Sendai",
    "Hiroshima",
  ],
  Brazilia: [
    "São Paulo",
    "Rio de Janeiro",
    "Belo Horizonte",
    "Brasília",
    "Fortaleza",
    "Salvador",
    "Curitiba",
    "Manaus",
    "Recife",
    "Porto Alegre",
  ],
  Mexic: [
    "Ciudad de México",
    "Guadalajara",
    "Monterrey",
    "Puebla",
    "Toluca",
    "Tijuana",
    "León",
    "Ciudad Juárez",
    "Cancún",
  ],
  Rusia: [
    "Moscova",
    "Sankt Petersburg",
    "Novosibirsk",
    "Ekaterinburg",
    "Nijni Novgorod",
    "Samara",
    "Omsk",
    "Kazan",
    "Chelyabinsk",
    "Rostov-pe-Don",
  ],
  India: [
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Hyderabad",
    "Ahmedabad",
    "Chennai",
    "Kolkata",
    "Surat",
    "Pune",
    "Jaipur",
  ],
  China: [
    "Shanghai",
    "Beijing",
    "Guangzhou",
    "Shenzhen",
    "Chengdu",
    "Xi'an",
    "Wuhan",
    "Tianjin",
    "Hangzhou",
    "Nanjing",
  ],
  "Africa de Sud": [
    "Johannesburg",
    "Cape Town",
    "Durban",
    "Pretoria",
    "Port Elizabeth",
    "Bloemfontein",
    "Nelspruit",
    "Kimberley",
  ],
  Argentina: [
    "Buenos Aires",
    "Córdoba",
    "Rosario",
    "Mendoza",
    "La Plata",
    "Tucumán",
    "Mar del Plata",
    "Salta",
    "Santa Fe",
  ],
  Egipt: [
    "Cairo",
    "Alexandria",
    "Giza",
    "Shubra El-Kheima",
    "Port Said",
    "Suez",
    "Luxor",
    "Mansoura",
    "El Mahalla el Kubra",
  ],
  Turcia: [
    "Istanbul",
    "Ankara",
    "Izmir",
    "Bursa",
    "Adana",
    "Gaziantep",
    "Konya",
    "Antalya",
    "Kayseri",
    "Mersin",
  ],
  "Coreea de Sud": [
    "Seoul",
    "Busan",
    "Incheon",
    "Daegu",
    "Daejeon",
    "Gwangju",
    "Suwon",
    "Ulsan",
    "Changwon",
    "Goyang",
  ],
  Nigeria: [
    "Lagos",
    "Kano",
    "Ibadan",
    "Kaduna",
    "Port Harcourt",
    "Benin City",
    "Maiduguri",
    "Zaria",
    "Aba",
    "Jos",
  ],
  Thailanda: [
    "Bangkok",
    "Chiang Mai",
    "Phuket",
    "Pattaya",
    "Krabi",
    "Ko Samui",
    "Hua Hin",
    "Ayutthaya",
  ],
  Grecia: [
    "Atena",
    "Salonic",
    "Corfu",
    "Santorini",
    "Creta",
    "Rhodos",
    "Mykonos",
    "Naxos",
  ],
  "Emiratele Arabe Unite": [
    "Dubai",
    "Abu Dhabi",
    "Sharjah",
    "Al Ain",
    "Ajman",
    "Ras al-Khaimah",
    "Fujairah",
    "Umm Al Quwain",
  ],
  Portugalia: [
    "Lisabona",
    "Porto",
    "Braga",
    "Funchal",
    "Coimbra",
    "Albufeira",
    "Aveiro",
    "Faro",
  ],
  Olanda: [
    "Amsterdam",
    "Rotterdam",
    "Utrecht",
    "Den Haag",
    "Eindhoven",
    "Tilburg",
    "Groningen",
    "Almere",
  ],
  Suedia: [
    "Stockholm",
    "Göteborg",
    "Malmö",
    "Uppsala",
    "Västerås",
    "Örebro",
    "Linköping",
    "Helsingborg",
  ],
  Norvegia: [
    "Oslo",
    "Bergen",
    "Trondheim",
    "Stavanger",
    "Kristiansand",
    "Fredrikstad",
    "Tromsø",
    "Drammen",
  ],
  Elveția: [
    "Zürich",
    "Geneva",
    "Basel",
    "Lausanne",
    "Bern",
    "Lucerne",
    "St. Gallen",
    "Lugano",
  ],
  Austria: [
    "Viena",
    "Graz",
    "Linz",
    "Salzburg",
    "Innsbruck",
    "Klagenfurt",
    "Wels",
    "Sankt Pölten",
  ],
  Belgia: [
    "Bruxelles",
    "Antwerp",
    "Ghent",
    "Charleroi",
    "Liège",
    "Bruges",
    "Namur",
    "Leuven",
  ],
  Cehia: [
    "Praga",
    "Brno",
    "Ostrava",
    "Plzeň",
    "Liberec",
    "Olomouc",
    "Ústí nad Labem",
    "Hradec Králové",
  ],
  Polonia: [
    "Varșovia",
    "Cracovia",
    "Wrocław",
    "Poznań",
    "Gdańsk",
    "Szczecin",
    "Bydgoszcz",
    "Lublin",
  ],
  Malaezia: [
    "Kuala Lumpur",
    "George Town",
    "Ipoh",
    "Shah Alam",
    "Petaling Jaya",
    "Johor Bahru",
    "Malacca City",
    "Kota Kinabalu",
  ],
  Indonezia: [
    "Jakarta",
    "Bali",
    "Surabaya",
    "Bandung",
    "Medan",
    "Yogyakarta",
    "Makassar",
    "Semarang",
  ],
  Filipine: [
    "Manila",
    "Quezon City",
    "Davao City",
    "Cebu City",
    "Zamboanga City",
    "Taguig",
    "Pasig",
    "Antipolo",
  ],
  Vietnam: [
    "Ho Chi Minh City",
    "Hanoi",
    "Da Nang",
    "Hai Phong",
    "Can Tho",
    "Bien Hoa",
    "Nha Trang",
    "Hue",
  ],
  Etiopia: [
    "Addis Ababa",
    "Dire Dawa",
    "Mekele",
    "Adama",
    "Gondar",
    "Awasa",
    "Bahir Dar",
    "Harar",
  ],
  Kenya: [
    "Nairobi",
    "Mombasa",
    "Kisumu",
    "Nakuru",
    "Eldoret",
    "Kehancha",
    "Ruiru",
    "Kikuyu",
  ],
  Columbia: [
    "Bogotá",
    "Medellín",
    "Cali",
    "Barranquilla",
    "Cartagena",
    "Cúcuta",
    "Bucaramanga",
    "Pereira",
  ],
};

export const transportSejur = ["Avion", "Autocar", "Individual"];
export const transportCircuit = ["Avion", "Autocar"];
